apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: filesure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: filesure-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
        env:
        - name: MONGO_URI
          value: "mongodb://mongodb:27017"
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: filesure
spec:
  ports:
  - port: 5001
    targetPort: 5001
  selector:
    app: api
  type: LoadBalancer  # For local testing, use NodePort if needed