apiVersion: v1
kind: Pod
metadata:
  name: test-mongodb-connection-keda
  namespace: keda
spec:
  containers:
  - name: test
    image: mongo:6.0
    command: ["mongosh"]
    args: ["--eval", "db.jobs.countDocuments({\"jobStatus\": \"pending\"})", "$(MONGO_URI)"]
    env:
    - name: MONGO_URI
      valueFrom:
        secretKeyRef:
          name: filesure-secrets
          key: mongo-uri
  restartPolicy: Never
