apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: filesure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      volumes:
      - name: mongodb-data
        emptyDir: {}  # Use persistent volume for production
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: filesure
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongodb
  clusterIP: None  # Headless service for direct pod access