apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: filesure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: filesure-worker:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9100
        env:
        - name: MONGO_URI
          value: "mongodb://mongodb:27017"
---
apiVersion: v1
kind: Service
metadata:
  name: worker
  namespace: filesure
spec:
  ports:
  - port: 9100
    targetPort: 9100
  selector:
    app: worker
  type: ClusterIP