
#Last worked version of the file before deletion
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: worker-scaledjob
  namespace: filesure
spec:
  jobTargetRef:
    template:
      spec:
        restartPolicy: Never
        containers:
        - name: worker
          image: filesure-worker:latest
          imagePullPolicy: IfNotPresent
          command: ["python", "-u", "worker/downloader.py"]
          env:
          - name: MONGO_URI
            valueFrom:
              secretKeyRef:
                name: filesure-secrets
                key: mongo-uri
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: filesure-secrets
                key: aws-access-key-id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: filesure-secrets
                key: aws-secret-access-key
          - name: AWS_REGION
            valueFrom:
              secretKeyRef:
                name: filesure-secrets
                key: aws-region
          - name: AWS_BUCKET_NAME
            valueFrom:
              secretKeyRef:
                name: filesure-secrets
                key: aws-bucket-name
          ports:  # Added for explicit exposure
          - containerPort: 9100
            name: metrics
  triggers:
  - type: mongodb
    metadata:
      dbName: filesure
      collection: jobs
      query: '{"jobStatus": "pending"}'
      queryValue: "1"
      activationQueryValue: "0"
    authenticationRef:
      name: mongodb-trigger-auth
  maxReplicaCount: 10
  pollingInterval: 5
  successfulJobsHistoryLimit: 10  # Increased to retain more for debugging
  failedJobsHistoryLimit: 10  # Increased to retain more for debugging