name: CI/CD Pipeline for FileSure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/filesure-api:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Worker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./worker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/filesure-worker:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-local:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Docker images from DockerHub
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/filesure-api:latest
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/filesure-worker:latest

      - name: Set up Kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.23.0"
          cluster-name: filesure-cluster
          config: kubernetes/kind-config.yaml

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Load Docker images into Kind cluster
        run: |
          kind load docker-image ${{ secrets.DOCKERHUB_USERNAME }}/filesure-api:latest --name filesure-cluster
          kind load docker-image ${{ secrets.DOCKERHUB_USERNAME }}/filesure-worker:latest --name filesure-cluster

      - name: Create Secrets in filesure namespace
        run: |
          kubectl create secret generic filesure-secrets -n filesure \
            --from-literal=mongo-uri=${{ secrets.MONGO_URI }} \
            --from-literal=aws-access-key-id=${{ secrets.AWS_ACCESS_KEY_ID }} \
            --from-literal=aws-secret-access-key=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            --from-literal=aws-region=${{ secrets.AWS_REGION }} \
            --from-literal=aws-bucket-name=${{ secrets.AWS_BUCKET_NAME }} \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Create Secrets in keda namespace
        run: |
          kubectl create secret generic filesure-secrets -n keda \
            --from-literal=mongo-uri=${{ secrets.MONGO_URI }} \
            --from-literal=aws-access-key-id=${{ secrets.AWS_ACCESS_KEY_ID }} \
            --from-literal=aws-secret-access-key=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            --from-literal=aws-region=${{ secrets.AWS_REGION }} \
            --from-literal=aws-bucket-name=${{ secrets.AWS_BUCKET_NAME }} \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f kubernetes/namespace.yml -n filesure
          kubectl apply -f kubernetes/mongodb.yml -n filesure
          kubectl apply -f kubernetes/api.yml -n filesure
          kubectl apply -f kubernetes/grafana.yml -n filesure
          kubectl apply -f kubernetes/prometheus.yml -n filesure
          kubectl apply -f kubernetes/mongodb-exporter.yml -n filesure
          kubectl apply -f kubernetes/worker-service.yml -n filesure
          kubectl apply -f keda/trigger-auth.yaml -n filesure
          kubectl apply -f keda/worker-scaledjob.yml -n filesure
          kubectl rollout restart scaledjob/worker-scaledjob -n filesure
          kubectl rollout restart deployment/api -n filesure
          kubectl rollout restart deployment/prometheus -n filesure
        env:
          KUBECONFIG: ~/.kube/config